# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-16 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=1500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='book_images')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rack_number', models.IntegerField(blank=True, null=True)),
                ('edition', models.CharField(blank=True, max_length=5, null=True)),
                ('available', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('mem_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_Membership', models.DateField(auto_now_add=True)),
                ('department', models.CharField(choices=[('Nursing', 'Nursing'), ('Radiography', 'Radiography'), ('HA', 'HA'), ('Laboratory', 'Laboratory')], max_length=50)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('number_of_Books_Issued', models.IntegerField(default='0')),
                ('maximum_Book_Limit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_Issue', models.DateField(auto_now_add=True)),
                ('due_Date', models.DateField()),
                ('status', models.CharField(default='borrowed', max_length=500)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.Book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.Member')),
            ],
        ),
    ]
